import "./globals.css";
// @mui material components
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/theme";
import DefaultNavbar from "@/components/examples/Navbars/DefaultNavbar";
import { routes } from "@/api/routes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <html lang="pt">
        <body>
          <DefaultNavbar
            routes={routes}
            brand={"Grupo Visual"}
            action={{
              type: "external",
              route: "https://www.creative-tim.com/product/material-kit-react",
              label: "free download",
              color: "info",
            }}
            sticky
          />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
