export const routes = [
  {
    name: "Cursos",
    route: "/cursos",
  },
  {
    name: "Sobre",
    columns: 1,
    rowsPerColumn: 2,
    collapse: [
      {
        collapse: [
          {
            name: "Quem Somos",
            route: "/quem-somos",
          },
          {
            name: "Nosso Método",
            route: "/quem-somos#nosso-metodo",
          },
          {
            name: "Professores",
            route: "/professores",
          },
        ],
      },
    ],
  },
  {
    name: "Contato",
    route: "/contato",
  },
  {
    name: "Blog",
    route: "/blog",
  },
];

export const courses = [
  {
    id: 1,
    price: 4.5,
    img: "/blog1.webp",
    stars: 3.4,
    text: "Alimentacao Social Asistida #2 con hambre",
    url: "/teste",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 2,
    price: 2,
    img: "/course2.webp",
    stars: 5,
    text: "Social Media",
    url: "/teste2",
    category: { color: "#aa0000", text: "Programacao", id: 2 },
  },
  {
    id: 3,
    price: 3,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleiro",
    url: "/teste3",
    category: { color: "#00aa00", text: "Empresa", id: 3 },
  },
  {
    id: 4,
    price: 2.5,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste4",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 5,
    price: 8,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste5",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 6,
    price: 10,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste6",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 7,
    price: 4,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste7",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 8,
    price: 2,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste8",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 9,
    price: 1,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste9",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 10,
    price: 2,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste10",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
  {
    id: 11,
    price: 4550.45,
    img: "/course3.webp",
    stars: 4.5,
    text: "Cabeleleir2o",
    url: "/teste11",
    category: { color: "#0000aa", text: "Marketing", id: 1 },
  },
];

export const teachers = [
  {
    id: 1,
    slug: "/jose1",
    url: "/student1.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
  {
    id: 2,
    slug: "/jose2",
    url: "/student1.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
  {
    id: 3,
    slug: "/jose3",
    url: "/student1.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
  {
    id: 4,
    slug: "/jose4",
    url: "/student1.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
  {
    id: 5,
    slug: "/jose5",
    url: "/student2.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
  {
    id: 6,
    slug: "/jose6",
    url: "/student2.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
  {
    id: 7,
    slug: "/jose7",
    url: "/student2.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
  {
    id: 8,
    slug: "/jose8",
    url: "/student2.webp",
    title: "Maria Javier",
    text: "Master en ciencias. Professora da PUCPR",
  },
];
